"""add is_read and read_at to feedback

Revision ID: 1557bf9c5212
Revises: 87ba6fc0fd42
Create Date: 2025-11-06 23:56:05.384535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1557bf9c5212'
down_revision = '87ba6fc0fd42'
branch_labels = None
depends_on = None


def upgrade():
    # Check if columns exist before adding them
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    cols = []
    try:
        cols = [c['name'] for c in inspector.get_columns('feedback')]
    except Exception:
        cols = []

    with op.batch_alter_table('feedback', schema=None) as batch_op:
        if 'is_read' not in cols:
            batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=False, server_default='0'))
        if 'read_at' not in cols:
            batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('read_at')
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
