"""empty message

Revision ID: e4c8e8f1b60e
Revises: 
Create Date: 2025-10-26 16:46:53.599449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c8e8f1b60e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('upload_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###
